version: "3.7"

services:
  user-management-service:
    build:
      context: ./user_managment
      dockerfile: Dockerfile
    container_name: user_management_service
    restart: always
    networks:
      - servers
    ports:
      - 8085:8085
    depends_on:
      - database

  auth-service:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    container_name: auth_service
    restart: always
    networks:
      - servers
    ports:
      - 8082:8082
    depends_on:
      - database

  blog-service:
    build:
      context: ./BlogService
      dockerfile: Dockerfile
    container_name: blog_service
    restart: always
    networks:
      - servers
    ports:
      - 8084:8084
    depends_on:
      - database

  tour-service:
    build:
      context: ./TourService
      dockerfile: Dockerfile
    container_name: tour_service
    restart: always
    networks:
      - servers
    ports:
      - 8086:8086
    environment:
      - PORT=8086
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017
    depends_on:
      - mongo

  database:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - servers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
    volumes:
      - database-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - servers
    ports:
      - 8083:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - servers
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - servers
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    ports:
      - 8081:8081
    volumes:
      - mongo_express_data:/data/db

volumes:
  database-data:
    name: server-database
  mongo_store:
  mongo_express_data:

networks:
  servers:
    name: servers
    driver: bridge
