version: "3.8"

services:
  tour-service:
    image: tour_service
    build:
      context: ./TourService
      dockerfile: Dockerfile
    container_name: tour_service
    hostname: tour_service
    restart: always
    networks:
      - network
    environment:
      MONGO_DB_URI: mongodb://root:pass@mongo:27017
      TOUR_SERVICE_ADDRESS: ${TOUR_SERVICE_ADDRESS}
    depends_on:
      - mongo


  blog-service:
    image: blog_service
    build:
      context: ./BlogService
      dockerfile: Dockerfile
    container_name: blog_service
    hostname: blog_service
    restart: always
    environment:
      BLOG_SERVICE_ADDRESS: ${BLOG_SERVICE_ADDRESS}
    networks:
      - network
    depends_on:
      - database

  auth-service:
    image: auth_service
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth_service
    hostname: auth_service
    restart: always
    environment:
      AUTH_SERVICE_ADDRESS: ${AUTH_SERVICE_ADDRESS}
    networks:
      - network
    depends_on:
      - database

  user-service:
    image: user_service
    build:
      context: ./UserManagementService
      dockerfile: Dockerfile
    container_name: user_service
    hostname: user_service
    restart: always
    environment:
      USER_MANAGEMENT_SERVICE_ADDRESS: ${USER_MANAGEMENT_SERVICE_ADDRESS}
    networks:
      - network
    depends_on:
      - database

  database:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
    volumes:
      - database-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - network
    ports:
      - 8083:8080

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    hostname: api_gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      TOUR_SERVICE_ADDRESS: tour_service:8086
      BLOG_SERVICE_ADDRESS: blog_service:8085
      AUTH_SERVICE_ADDRESS: auth_service:8084
      USER_MANAGEMENT_SERVICE_ADDRESS: user_service:8089
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS}
    depends_on:
      - tour-service
      - blog-service
      - auth-service
      - user-service
    networks:
      - network
    ports:
      - "8087:8087"

  grafana:
    image: grafana/grafana:8.5.3
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

  renderer:
    image: grafana/grafana-image-renderer:3.10.5
    environment:
      ENABLE_METRICS: "true"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.35.0
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus:/var/lib/prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.1.2
    ports:
      - "9100:9100"
    networks:
      - monitoring

  mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      networks:
        - network
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
        MONGO_INITDB_DATABASE: mongoDemo
      healthcheck:
        test: echo 'db.runCommand("ping").ok'
        interval: 10s
        timeout: 10s
        retries: 10
      volumes:
        - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    ports:
      - 8081:8081
    volumes:
      - mongo_express_data:/data/db

volumes:
  database-data:
    name: server-database
  mongo_store:
  mongo_express_data:
  grafana:
    name: grafana
  prometheus:
    name: prometheus

networks:
  network:
    driver: bridge
  monitoring:
    name: monitoring